apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
