name: implementing CI/CD for go app
on:
  push:
    branches:
      - main
    paths-ignore:
     - 'helm/**'
     - 'k8s/**'
     - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: build
        run: go build -o go-app
      - name: run test
        run: go test ./...
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.0
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}
      - name: build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/go-demo:${{ github.run_id }}
  update-newtag-in-helm-charts:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: update tag in helm chart
        run: |
          sed -i "s/tag: .*/tag: ${{ vars.DOCKER_USERNAME }}\"/'helm/go-app-chart/values.yaml
      - name: commit and push changes
        run: |
          git config --local user.email "yugandharkanaparthi9@gmail.com"
          git config --local user.name "Yugandhar Kanaparthi"
          git add helm/go-app-chart/values.yaml
          git commit -m "Update image tag"
          git push